version: '3.8'
services:
  app-dev:
    container_name: nestjs-app-dev
    build:
      context: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app # Monta o diretório local
    command: npm run start:dev
