import { MigrationInterface, QueryRunner } from "typeorm";

export class SchemaUpdate1730209751659 implements MigrationInterface {
    name = 'SchemaUpdate1730209751659'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "TB_PRODUCT_DETAILS" ("CD_PRODUCT_DETAIL" number GENERATED BY DEFAULT AS IDENTITY, "URL" varchar2(255) NOT NULL, "DE_PRODUCT_DETAIL" varchar2(255) NOT NULL, CONSTRAINT "PK_b48434b64914b1c0edb3d84d0fe" PRIMARY KEY ("CD_PRODUCT_DETAIL"))`);
        await queryRunner.query(`CREATE TABLE "TB_PRODUCT_IMAGES" ("CD_PRODUCT_IMAGE" number GENERATED BY DEFAULT AS IDENTITY, "URL" varchar2(255) NOT NULL, "DE_PRODUCT_IMAGE" varchar2(255) NOT NULL, CONSTRAINT "PK_dc725f38d4633d8cdd1e9158f23" PRIMARY KEY ("CD_PRODUCT_IMAGE"))`);
        await queryRunner.query(`ALTER TABLE "TB_PRODUCTS" ADD "CD_PRODUCT_CATEGORY" number`);
        await queryRunner.query(`ALTER TABLE "TB_PRODUCTS" ADD CONSTRAINT "UQ_62fa2ee2e8e8671cfca82182fb8" UNIQUE ("CD_PRODUCT_CATEGORY")`);
        await queryRunner.query(`ALTER TABLE "TB_PRODUCTS" ADD CONSTRAINT "FK_62fa2ee2e8e8671cfca82182fb8" FOREIGN KEY ("CD_PRODUCT_CATEGORY") REFERENCES "TB_PRODUCT_CATEGORIES" ("CD_PRODUCT_CATEGORY")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "TB_PRODUCTS" DROP CONSTRAINT "FK_62fa2ee2e8e8671cfca82182fb8"`);
        await queryRunner.query(`ALTER TABLE "TB_PRODUCTS" DROP CONSTRAINT "UQ_62fa2ee2e8e8671cfca82182fb8"`);
        await queryRunner.query(`ALTER TABLE "TB_PRODUCTS" DROP COLUMN "CD_PRODUCT_CATEGORY"`);
        await queryRunner.query(`DROP TABLE "TB_PRODUCT_IMAGES"`);
        await queryRunner.query(`DROP TABLE "TB_PRODUCT_DETAILS"`);
    }

}
